package com.ronaldo.analizadorlexico.frontend;

import com.ronaldo.analizadorlexico.frontend.dialogs.EditorJson;
import com.ronaldo.analizadorlexico.backend.Motor;
import com.ronaldo.analizadorlexico.backend.enums.Extension;
import com.ronaldo.analizadorlexico.frontend.dialogs.ReporteErroresDialog;
import com.ronaldo.analizadorlexico.frontend.dialogs.ReporteTokensDialog;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author ronaldo
 */
public class FramePrincipal extends javax.swing.JFrame {
       private Motor motor;
       private JTextArea lineaDeNumerosEntrada;
       private JTextArea lineaDeNumerosSalida;
       private File fileEntrada;
       private File fileConfig;
       private boolean escuchadorActivado;
       private DocumentListener listener;
       private File archivoJson;

       /**
        * Creates new form FramePrincipal
        */
       public FramePrincipal(Motor motor) {
              initComponents();
              escuchadorActivado=true;
              lineaDeNumerosEntrada = new JTextArea("1");
              lineaDeNumerosSalida = new JTextArea("1");
              this.motor = motor;
              inicializarNumeroDeLineas(scrollPaneAreaEntrada, txtPaneEntrada, lineaDeNumerosEntrada);
              inicializarNumeroDeLineas(scrollPaneSalida, txtPaneSalida, lineaDeNumerosSalida);
              inicializarEscuchadorTextoEntrada();
              toggleEscuchador(escuchadorActivado);
              btnEditarConfig.setEnabled(false);
       }

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              lblEncabezado = new javax.swing.JLabel();
              contenedorCarga = new javax.swing.JPanel();
              btnCargaArchivo = new javax.swing.JButton();
              scrollPaneAreaEntrada = new javax.swing.JScrollPane();
              txtPaneEntrada = new javax.swing.JTextPane();
              txtBusqueda = new javax.swing.JTextField();
              btnBuscar = new javax.swing.JButton();
              scrollPaneSalida = new javax.swing.JScrollPane();
              txtPaneSalida = new javax.swing.JTextPane();
              btnCargaDatos = new javax.swing.JButton();
              btnEditarConfig = new javax.swing.JButton();
              panelReportes = new javax.swing.JPanel();
              btnReporteErrores = new javax.swing.JButton();
              btnReporteTokens = new javax.swing.JButton();
              btnReporteGeneral = new javax.swing.JButton();

              setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

              contenedor.setBackground(new java.awt.Color(255, 255, 204));

              lblEncabezado.setBackground(new java.awt.Color(153, 51, 0));
              lblEncabezado.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 48)); // NOI18N
              lblEncabezado.setForeground(new java.awt.Color(0, 0, 0));
              lblEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblEncabezado.setText("ANALIZADOR LEXICO");
              lblEncabezado.setOpaque(true);

              contenedorCarga.setBackground(new java.awt.Color(204, 204, 204));
              contenedorCarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

              btnCargaArchivo.setText("CARGAR ARCHIVO");
              btnCargaArchivo.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnCargaArchivoActionPerformed(evt);
                     }
              });

              txtPaneEntrada.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
              scrollPaneAreaEntrada.setViewportView(txtPaneEntrada);

              txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            txtBusquedaActionPerformed(evt);
                     }
              });

              btnBuscar.setText("Buscar Palabra");
              btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnBuscarActionPerformed(evt);
                     }
              });

              txtPaneSalida.setEditable(false);
              txtPaneSalida.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
              scrollPaneSalida.setViewportView(txtPaneSalida);

              btnCargaDatos.setText("CARGAR CONFIG");
              btnCargaDatos.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnCargaDatosActionPerformed(evt);
                     }
              });

              btnEditarConfig.setText("EDITAR CONFIG");
              btnEditarConfig.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnEditarConfigActionPerformed(evt);
                     }
              });

              javax.swing.GroupLayout contenedorCargaLayout = new javax.swing.GroupLayout(contenedorCarga);
              contenedorCarga.setLayout(contenedorCargaLayout);
              contenedorCargaLayout.setHorizontalGroup(
                     contenedorCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorCargaLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorCargaLayout.createSequentialGroup()
                            .addGroup(contenedorCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(contenedorCargaLayout.createSequentialGroup()
                                          .addGap(18, 18, 18)
                                          .addGroup(contenedorCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                 .addComponent(scrollPaneSalida)
                                                 .addComponent(scrollPaneAreaEntrada)))
                                   .addGroup(contenedorCargaLayout.createSequentialGroup()
                                          .addGap(40, 40, 40)
                                          .addComponent(btnCargaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(btnCargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addComponent(btnEditarConfig)
                                          .addGap(3, 3, 3)))
                            .addGap(37, 37, 37))
              );
              contenedorCargaLayout.setVerticalGroup(
                     contenedorCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorCargaLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(contenedorCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(btnCargaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(btnEditarConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(btnCargaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scrollPaneAreaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contenedorCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                   .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(scrollPaneSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addGap(14, 14, 14))
              );

              panelReportes.setBackground(new java.awt.Color(0, 153, 153));
              panelReportes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

              btnReporteErrores.setText("Reporte Errores");
              btnReporteErrores.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnReporteErroresActionPerformed(evt);
                     }
              });

              btnReporteTokens.setText("Reporte Tokens");
              btnReporteTokens.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnReporteTokensActionPerformed(evt);
                     }
              });

              btnReporteGeneral.setText("Reporte General");
              btnReporteGeneral.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnReporteGeneralActionPerformed(evt);
                     }
              });

              javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
              panelReportes.setLayout(panelReportesLayout);
              panelReportesLayout.setHorizontalGroup(
                     panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(panelReportesLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(btnReporteErrores)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnReporteTokens)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReporteGeneral)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              panelReportesLayout.setVerticalGroup(
                     panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(panelReportesLayout.createSequentialGroup()
                            .addContainerGap(13, Short.MAX_VALUE)
                            .addGroup(panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(btnReporteErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(btnReporteTokens, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(btnReporteGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(14, Short.MAX_VALUE))
              );

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(panelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(contenedorCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(17, 17, 17))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(contenedorCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(panelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(16, 16, 16))
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnCargaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaArchivoActionPerformed
              boolean estadoOriginal = this.escuchadorActivado;

              if (estadoOriginal) {
                     toggleEscuchador(false);
              }
              JFileChooser chooserArchivo = new JFileChooser();
              chooserArchivo.setDialogTitle("Archivo de entrada");
              FileNameExtensionFilter filtro = new FileNameExtensionFilter("archivo de texto", "txt");
              chooserArchivo.setFileFilter(filtro);
              chooserArchivo.setAcceptAllFileFilterUsed(false);

              int seleccionado = chooserArchivo.showOpenDialog(this);

              if (seleccionado == JFileChooser.APPROVE_OPTION) {
                     File archivoDeEntrada = chooserArchivo.getSelectedFile();
                     motor.realizarAccionesAccionesTexto(archivoDeEntrada, txtPaneEntrada);
                     
              }

              if (estadoOriginal) {
                     toggleEscuchador(true);
              }
       }//GEN-LAST:event_btnCargaArchivoActionPerformed

       private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
              File archivo = obtenerFile(Extension.TXT.getExtension(), fileEntrada);
              if (archivo == null) {
                     return;
              }
              motor.getCargador().pedirLecturaArchivo(archivo, txtPaneEntrada);
              
              actualizarNumeroDeLinea(lineaDeNumerosEntrada, txtPaneEntrada);
           
       }//GEN-LAST:event_txtBusquedaActionPerformed


       private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
              motor.buscarPalabra(txtPaneSalida, txtBusqueda.getText());
              
       }//GEN-LAST:event_btnBuscarActionPerformed

       private void btnCargaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaDatosActionPerformed
              File file = obtenerFile(Extension.JSON.getExtension(), fileConfig);
              if (file == null) {
                     return;
              }
              archivoJson = file;
              motor.leerYCargarJson(archivoJson);
              btnEditarConfig.setEnabled(true);
       }//GEN-LAST:event_btnCargaDatosActionPerformed

       private void btnEditarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConfigActionPerformed
              EditorJson dialog = new EditorJson(archivoJson, motor, this);
              dialog.setVisible(true);
       }//GEN-LAST:event_btnEditarConfigActionPerformed

       private void btnReporteErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteErroresActionPerformed
              ReporteErroresDialog dialog = new ReporteErroresDialog(motor.getAlmacenTokens().getListaTokens());
              dialog.setVisible(true);
       }//GEN-LAST:event_btnReporteErroresActionPerformed

       private void btnReporteTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteTokensActionPerformed
              if(motor.getAlmacenTokens().todosLosTokensSonCorrectos()){
                     ReporteTokensDialog dialog = new ReporteTokensDialog(motor.getAlmacenTokens().getListaTokens());
                     dialog.setVisible(true);
              }
              else{
                     JOptionPane.showMessageDialog(this, "se habilita cuando no hay errores", "No se puede abrir", JOptionPane.INFORMATION_MESSAGE);
              }
       }//GEN-LAST:event_btnReporteTokensActionPerformed

       private void btnReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteGeneralActionPerformed
              motor.crearReporteGeneral();
       }//GEN-LAST:event_btnReporteGeneralActionPerformed

       private File obtenerFile(String extension, File file) {
              JFileChooser chooserArchivo = new JFileChooser();
              chooserArchivo.setDialogTitle("Archivo ");
              FileNameExtensionFilter filtro = new FileNameExtensionFilter("archivo ", extension);
              chooserArchivo.setFileFilter(filtro);
              chooserArchivo.setAcceptAllFileFilterUsed(false);
              
              int seleccionado = chooserArchivo.showOpenDialog(this);
              
              if (seleccionado == JFileChooser.APPROVE_OPTION) {
                     file = chooserArchivo.getSelectedFile();
              }
              return file;
       }

       public void inicializarNumeroDeLineas(JScrollPane scrollpane, JTextPane txtPane, JTextArea lineaDeNumeros) {
              lineaDeNumeros.setEditable(false);
              lineaDeNumeros.setBackground(Color.MAGENTA);
              lineaDeNumeros.setFont(new Font("Monospaced", Font.PLAIN, 17));
              scrollpane.setRowHeaderView(lineaDeNumeros);

              // Escucha cambios en el documento
              txtPane.getDocument().addDocumentListener(new DocumentListener() {
                     @Override
                     public void insertUpdate(DocumentEvent e) {
                            actualizarNumeroDeLinea(lineaDeNumeros, txtPane);
                            
                     }
                     @Override
                     public void removeUpdate(DocumentEvent e) {
                            actualizarNumeroDeLinea(lineaDeNumeros, txtPane);
                     }
                     @Override
                     public void changedUpdate(DocumentEvent e) {
                     }
              });
              actualizarNumeroDeLinea(lineaDeNumeros, txtPane);
       }




       public void inicializarEscuchadorTextoEntrada() {
              if (escuchadorActivado) {
                     listener = new DocumentListener() {
                            public void insertUpdate(DocumentEvent e) {
                                   motor.realizarAccionesEdicionTexto(txtPaneEntrada);
                            }
                            public void removeUpdate(DocumentEvent e) {
                                   motor.realizarAccionesEdicionTexto(txtPaneEntrada);
                            }
                            public void changedUpdate(DocumentEvent e) {
                            
                            }
                     };
                     txtPaneEntrada.getDocument().addDocumentListener(listener);
              }
       }

       public void toggleEscuchador(boolean activar) {
              if (activar && !escuchadorActivado) {
                     txtPaneEntrada.getDocument().addDocumentListener(listener);
                     escuchadorActivado = true;
              } else if (!activar && escuchadorActivado) {
                     txtPaneEntrada.getDocument().removeDocumentListener(listener);
                     escuchadorActivado = false;
              }
       }

       private void actualizarNumeroDeLinea(JTextArea lineaDeNumeros, JTextPane txtPane) {
              try {
                     int totalLineas = txtPane.getDocument().getDefaultRootElement().getElementCount();

                     String numeros = "";
                     for (int i = 1; i <= totalLineas; i++) {
                            numeros += i + "\n";
                     }

                     lineaDeNumeros.setText(numeros);

              } catch (Exception e) {
                     lineaDeNumeros.setText("1");
              }
       }

       public static JTextPane getTxtPaneEntrada() {
              return txtPaneEntrada;
       }

       public JTextPane getTxtPaneSalida() {
              return txtPaneSalida;
       }

       public File getArchivoJson() {
              return archivoJson;
       }
       
       public void setArchivoJson(File file){
              archivoJson=file;
       }
       
       
       
       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnBuscar;
       private javax.swing.JButton btnCargaArchivo;
       private javax.swing.JButton btnCargaDatos;
       private javax.swing.JButton btnEditarConfig;
       private javax.swing.JButton btnReporteErrores;
       private javax.swing.JButton btnReporteGeneral;
       private javax.swing.JButton btnReporteTokens;
       private javax.swing.JPanel contenedor;
       private javax.swing.JPanel contenedorCarga;
       private javax.swing.JLabel lblEncabezado;
       private javax.swing.JPanel panelReportes;
       private javax.swing.JScrollPane scrollPaneAreaEntrada;
       private javax.swing.JScrollPane scrollPaneSalida;
       private javax.swing.JTextField txtBusqueda;
       private static javax.swing.JTextPane txtPaneEntrada;
       private javax.swing.JTextPane txtPaneSalida;
       // End of variables declaration//GEN-END:variables
}
