package com.ronaldo.analizadorlexico.frontend.dialogs;

import com.ronaldo.analizadorlexico.backend.Motor;
import com.ronaldo.analizadorlexico.backend.almacenamiento.DefinicionToken;
import com.ronaldo.analizadorlexico.backend.escritura.Escritor;
import com.ronaldo.analizadorlexico.frontend.FramePrincipal;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class EditorJsonDialog extends javax.swing.JDialog {
       private File file;
       private Escritor escritor;
       private FramePrincipal frame;
       private Motor motor;
       private int indiceSeleccionado;
       private boolean habilitado;
       /**
        * Creates new form EditorJsonDialog
        */
       public EditorJsonDialog(File file, Motor motor, FramePrincipal frame) {
              initComponents();
              this.motor = motor;
              this.file = file;
              this.frame = frame;
              escritor = new Escritor();
              setLocationRelativeTo(null);
              alertanBotones();
       }

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              jLabel1 = new javax.swing.JLabel();
              btnSalir = new javax.swing.JButton();
              jPanel1 = new javax.swing.JPanel();
              cmbTipos = new javax.swing.JComboBox<>();
              jLabel2 = new javax.swing.JLabel();
              btnSelecciona = new javax.swing.JButton();
              jPanel2 = new javax.swing.JPanel();
              btnAgregar = new javax.swing.JButton();
              btnEliminar = new javax.swing.JButton();
              btnVer = new javax.swing.JButton();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
              setModal(true);

              contenedor.setBackground(new java.awt.Color(0, 153, 255));

              jLabel1.setBackground(new java.awt.Color(0, 153, 153));
              jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 48)); // NOI18N
              jLabel1.setForeground(new java.awt.Color(0, 0, 0));
              jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel1.setText("EDICION CONFIG.JSON");
              jLabel1.setOpaque(true);

              btnSalir.setText("SALIR");
              btnSalir.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnSalirActionPerformed(evt);
                     }
              });

              jPanel1.setBackground(new java.awt.Color(204, 204, 204));
              jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

              cmbTipos.setFont(new java.awt.Font("Monospaced", 0, 19)); // NOI18N
              cmbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palabras Reservadas", "Operadores Aritmeticos", "Signos De Puntuacion", "Signos De Agrupacion", "Comentario De Linea", "Comentario Bloque Inicio", "Comentario Bloque Fin" }));

              jLabel2.setForeground(new java.awt.Color(0, 0, 0));
              jLabel2.setText("SELECCIONA EL TIPO");

              btnSelecciona.setText("SELECCIONAR");
              btnSelecciona.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnSeleccionaActionPerformed(evt);
                     }
              });

              jPanel2.setBackground(new java.awt.Color(255, 255, 204));
              jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

              btnAgregar.setText("Agregar");
              btnAgregar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnAgregarActionPerformed(evt);
                     }
              });

              btnEliminar.setText("Eliminar");
              btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnEliminarActionPerformed(evt);
                     }
              });

              btnVer.setText("Ver");
              btnVer.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnVerActionPerformed(evt);
                     }
              });

              javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
              jPanel2.setLayout(jPanel2Layout);
              jPanel2Layout.setHorizontalGroup(
                     jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addContainerGap())
              );
              jPanel2Layout.setVerticalGroup(
                     jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                          .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                 .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addGroup(jPanel2Layout.createSequentialGroup()
                                          .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addContainerGap())))
              );

              javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
              jPanel1.setLayout(jPanel1Layout);
              jPanel1Layout.setHorizontalGroup(
                     jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addGap(161, 161, 161)
                                          .addComponent(jLabel2))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addGap(69, 69, 69)
                                          .addComponent(cmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(30, 30, 30)
                                          .addComponent(btnSelecciona))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addGap(22, 22, 22)
                                          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(27, Short.MAX_VALUE))
              );
              jPanel1Layout.setVerticalGroup(
                     jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(btnSelecciona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(cmbTipos, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(25, Short.MAX_VALUE))
              );

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(31, Short.MAX_VALUE))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addGap(34, 34, 34)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34))
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
              
              this.dispose();
       }//GEN-LAST:event_btnSalirActionPerformed

       private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
              String texto = obtenerNuevoElemento();
              if(texto==null){
                     return;
              }
              motor.getVerificador().getArchivador().agregarElementoDefinicion(indiceSeleccionado, texto);
              escritor.reescribirArchivo(motor.getVerificador().getArchivador().darDefinicionesJson(), file);
              habilitado=false;
              alertanBotones();
       }//GEN-LAST:event_btnAgregarActionPerformed

       private void btnSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionaActionPerformed
              indiceSeleccionado =cmbTipos.getSelectedIndex();
              habilitado=true;
              alertanBotones();
       }//GEN-LAST:event_btnSeleccionaActionPerformed

       private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
              DefinicionToken definicion=motor.getVerificador().
                      getArchivador().getListadoDefinicionTokens().get(indiceSeleccionado);
              
              EliminarDialog eliminar = new EliminarDialog(definicion);
              eliminar.setVisible(true);
              escritor.reescribirArchivo(motor.getVerificador().getArchivador().darDefinicionesJson(), file);
              habilitado = false;
              alertanBotones();
       }//GEN-LAST:event_btnEliminarActionPerformed

       private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
            String contenido=motor.getCargador().getLector().leerConfiguracion(file);
            VerJsonDialog ver = new VerJsonDialog(contenido);
            ver.setVisible(true);
            
       }//GEN-LAST:event_btnVerActionPerformed

       private void alertanBotones() {
                     btnEliminar.setEnabled(habilitado);
                     btnAgregar.setEnabled(habilitado);
       }

       public String obtenerNuevoElemento() {
              String elemento = JOptionPane.showInputDialog("Ingrese el nuevo elemento:");
              if (elemento == null) {
                     JOptionPane.showMessageDialog(this, "debes ingresar un elemento ");
                     return null;
              }
              if (elemento.contains(" ") || elemento.isEmpty()) {
                     JOptionPane.showMessageDialog(this, "el elemento no debe contener espacios ");
                     return null;
              }
              return elemento;
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnAgregar;
       private javax.swing.JButton btnEliminar;
       private javax.swing.JButton btnSalir;
       private javax.swing.JButton btnSelecciona;
       private javax.swing.JButton btnVer;
       private javax.swing.JComboBox<String> cmbTipos;
       private javax.swing.JPanel contenedor;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel2;
       private javax.swing.JPanel jPanel1;
       private javax.swing.JPanel jPanel2;
       // End of variables declaration//GEN-END:variables
}
