package com.ronaldo.analizadorlexico.frontend.dialogs;

import com.ronaldo.analizadorlexico.backend.Motor;
import com.ronaldo.analizadorlexico.backend.escritura.Escritor;
import com.ronaldo.analizadorlexico.frontend.FramePrincipal;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class EditorJson extends javax.swing.JDialog {
       private File file;
       private Escritor escritor;
       private FramePrincipal frame;
       private Motor motor;
       /**
        * Creates new form EditorJson
        */
       public EditorJson(File file, Motor motor, FramePrincipal frame) {
              initComponents();
              this.motor=motor;
              this.file=file;
              this.frame= frame;
              escritor= new Escritor();
              
              motor.getCargador().getLector().leerConfiguracion(file, txtPaneEntrada);
       }

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              jLabel1 = new javax.swing.JLabel();
              scollContenendor = new javax.swing.JScrollPane();
              txtPaneEntrada = new javax.swing.JTextPane();
              btnGuardar = new javax.swing.JButton();
              jButton1 = new javax.swing.JButton();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
              setModal(true);

              contenedor.setBackground(new java.awt.Color(0, 153, 255));

              jLabel1.setBackground(new java.awt.Color(0, 153, 153));
              jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 48)); // NOI18N
              jLabel1.setForeground(new java.awt.Color(0, 0, 0));
              jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel1.setText("EDICION CONFIG.JSON");
              jLabel1.setOpaque(true);

              scollContenendor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

              txtPaneEntrada.setFont(new java.awt.Font("Monospaced", 0, 19)); // NOI18N
              scollContenendor.setViewportView(txtPaneEntrada);

              btnGuardar.setText("GUARDAR CAMBIOS");
              btnGuardar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnGuardarActionPerformed(evt);
                     }
              });

              jButton1.setText("SALIR");
              jButton1.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton1ActionPerformed(evt);
                     }
              });

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1317, Short.MAX_VALUE)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(scollContenendor)
                            .addGap(17, 17, 17))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(scollContenendor, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                   .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(34, 34, 34))
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(0, 0, 0))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(0, 0, 0))
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
              String texto = txtPaneEntrada.getText();
              frame.setArchivoJson(escritor.reescribirArchivo(texto, file));
              motor.leerYCargarJson(frame.getArchivoJson());
              JOptionPane.showMessageDialog(this, "Edicion exitosa", "edicion de configuracion", JOptionPane.INFORMATION_MESSAGE);
              this.dispose();
       }//GEN-LAST:event_btnGuardarActionPerformed

       private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              this.dispose();
       }//GEN-LAST:event_jButton1ActionPerformed


       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnGuardar;
       private javax.swing.JPanel contenedor;
       private javax.swing.JButton jButton1;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JScrollPane scollContenendor;
       private javax.swing.JTextPane txtPaneEntrada;
       // End of variables declaration//GEN-END:variables
}
