package com.ronaldo.analizadorlexico.frontend.dialogs;

import com.ronaldo.analizadorlexico.backend.almacenamiento.DefinicionToken;
import javax.swing.JOptionPane;

/**
 *
 * @author ronaldo
 */
public class EliminarDialog extends javax.swing.JDialog {
       private DefinicionToken definicion;

       /**
        * Creates new form Editor
        */
       public EliminarDialog(DefinicionToken definicion) {
              initComponents();
              setLocationRelativeTo(null);
              this.definicion=definicion;
              cargarCmb();
       }

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              cmbListadoElementos = new javax.swing.JComboBox<>();
              btnEliminar = new javax.swing.JButton();
              jButton1 = new javax.swing.JButton();
              jLabel1 = new javax.swing.JLabel();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
              setTitle("Eliminacion Elemento");
              setModal(true);

              contenedor.setBackground(new java.awt.Color(204, 255, 204));

              btnEliminar.setText("Eliminar");
              btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnEliminarActionPerformed(evt);
                     }
              });

              jButton1.setText("Salir");
              jButton1.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton1ActionPerformed(evt);
                     }
              });

              jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
              jLabel1.setForeground(new java.awt.Color(0, 0, 0));
              jLabel1.setText("ELIMINACION DE ELEMENTOS");
              jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(cmbListadoElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(92, Short.MAX_VALUE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addGap(205, 205, 205)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel1)
                            .addGap(34, 34, 34)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(cmbListadoElementos, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                   .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14))
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(0, 0, 0))
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
              int indiceElemento=cmbListadoElementos.getSelectedIndex();
              if(indiceElemento==-1){
                     JOptionPane.showMessageDialog(this, "Ya no hay elementos por eliminar");
                     this.dispose();
                     return;
              }
              definicion.getElementos().remove(indiceElemento);
              JOptionPane.showMessageDialog(this, "Eliminacion Correcta");
              cargarCmb();
       }//GEN-LAST:event_btnEliminarActionPerformed


       private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              this.dispose();
       }//GEN-LAST:event_jButton1ActionPerformed

       private void cargarCmb(){
              cmbListadoElementos.removeAllItems();
              for (int i = 0; i <definicion.getElementos().size(); i++) {
                     cmbListadoElementos.addItem(definicion.getElementos().get(i));
              }
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnEliminar;
       private javax.swing.JComboBox<String> cmbListadoElementos;
       private javax.swing.JPanel contenedor;
       private javax.swing.JButton jButton1;
       private javax.swing.JLabel jLabel1;
       // End of variables declaration//GEN-END:variables
}
