package com.ronaldo.analizadorlexico.frontend.dialogs;

import com.ronaldo.analizadorlexico.backend.ResumenLexema;
import com.ronaldo.analizadorlexico.backend.token.Token;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo
 */
public class ReporteTokensDialog extends javax.swing.JDialog {

       /**
        * Creates new form ReporteTokensDialog
        */
       public ReporteTokensDialog(List<Token> tokens, List<ResumenLexema>resumenes) {
              initComponents();
              cargarTabla(tokens);
              cargarTablaLexemas(resumenes);
       }

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              jLabel1 = new javax.swing.JLabel();
              jScrollPane1 = new javax.swing.JScrollPane();
              tablaTokens = new javax.swing.JTable();
              btnCerrar = new javax.swing.JButton();
              jScrollPane2 = new javax.swing.JScrollPane();
              tablaRecuento = new javax.swing.JTable();
              jLabel2 = new javax.swing.JLabel();
              jLabel3 = new javax.swing.JLabel();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
              setModal(true);

              contenedor.setBackground(new java.awt.Color(204, 204, 204));

              jLabel1.setBackground(new java.awt.Color(255, 51, 0));
              jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 48)); // NOI18N
              jLabel1.setForeground(new java.awt.Color(0, 0, 0));
              jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel1.setText("REPORTE DE TOKENS");
              jLabel1.setOpaque(true);

              tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
                     new Object [][] {

                     },
                     new String [] {
                            "Nombre Token", "Lexema", "Fila", "Columna"
                     }
              ));
              jScrollPane1.setViewportView(tablaTokens);

              btnCerrar.setText("Cerrar");
              btnCerrar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnCerrarActionPerformed(evt);
                     }
              });

              tablaRecuento.setModel(new javax.swing.table.DefaultTableModel(
                     new Object [][] {

                     },
                     new String [] {
                            "Lexema", "Tipo Token", "Cantidad Repetida"
                     }
              ));
              jScrollPane2.setViewportView(tablaRecuento);

              jLabel2.setForeground(new java.awt.Color(0, 0, 0));
              jLabel2.setText("TODOS LO TOKENS");

              jLabel3.setForeground(new java.awt.Color(0, 0, 0));
              jLabel3.setText("RECUENTO DE LEXEMAS");

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addGap(327, 327, 327)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                                   .addComponent(jScrollPane2))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
              this.dispose();
       }//GEN-LAST:event_btnCerrarActionPerformed

       private void cargarTabla(List<Token> tokens) {
              if (tokens == null) {
                     JOptionPane.showMessageDialog(this, "no hay errores para el reporte", "sin errores", JOptionPane.INFORMATION_MESSAGE);
                     return;
              }
              DefaultTableModel modelo = (DefaultTableModel) tablaTokens.getModel();
              for (int i = 0; i < tokens.size(); i++) {
                     modelo.addRow(new Object[]{tokens.get(i).getTipo(), tokens.get(i).getLexema(),
                            tokens.get(i).getFila() + 1, tokens.get(i).getColumna() + 1});

              }
       }
       
       private void cargarTablaLexemas(List<ResumenLexema> resumenes) {
              if (resumenes == null) {
                     JOptionPane.showMessageDialog(this, "no hay errores para el reporte", "sin errores", JOptionPane.INFORMATION_MESSAGE);
                     return;
              }
              DefaultTableModel modelo = (DefaultTableModel) tablaRecuento.getModel();
              for (int i = 0; i < resumenes.size(); i++) {
                     modelo.addRow(new Object[]{resumenes.get(i).getLexema(), resumenes.get(i).getTipo(),
                            resumenes.get(i).getCantidadRepetida()});

              }
       }
       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnCerrar;
       private javax.swing.JPanel contenedor;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel2;
       private javax.swing.JLabel jLabel3;
       private javax.swing.JScrollPane jScrollPane1;
       private javax.swing.JScrollPane jScrollPane2;
       private javax.swing.JTable tablaRecuento;
       private javax.swing.JTable tablaTokens;
       // End of variables declaration//GEN-END:variables
}
