package com.ronaldo.analizadorlexico.frontend.dialogs;

/**
 *
 * @author ronaldo
 */
public class ReporteGeneralDialogo extends javax.swing.JDialog {

       /**
        * Creates new form ReporteGeneralDialogo
        */
       public ReporteGeneralDialogo(int cantidadErrores, double porcentajeValidos, String [] tokensNoUtilizados) {
              initComponents();
              String errores=lblCantidadErrores.getText()+" "+cantidadErrores;
              lblCantidadErrores.setText(errores);
              String porcentaje =lblPorcentajeValidos.getText()+" "+porcentajeValidos +" %";
              lblPorcentajeValidos.setText(porcentaje);
              cargarTokensNoUtilizados(tokensNoUtilizados);
       }      

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              jLabel1 = new javax.swing.JLabel();
              jPanel1 = new javax.swing.JPanel();
              lblCantidadErrores = new javax.swing.JLabel();
              lblPorcentajeValidos = new javax.swing.JLabel();
              lblTokensNoUtilizados = new javax.swing.JLabel();
              btnSalir = new javax.swing.JButton();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
              setModal(true);

              contenedor.setBackground(new java.awt.Color(255, 255, 204));

              jLabel1.setBackground(new java.awt.Color(51, 204, 0));
              jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 48)); // NOI18N
              jLabel1.setForeground(new java.awt.Color(0, 0, 0));
              jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel1.setText("REPORTE GENERAL");
              jLabel1.setOpaque(true);

              jPanel1.setBackground(new java.awt.Color(204, 204, 204));
              jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

              lblCantidadErrores.setForeground(new java.awt.Color(0, 0, 0));
              lblCantidadErrores.setText("CANTIDAD DE ERRORES: ");
              lblCantidadErrores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

              lblPorcentajeValidos.setForeground(new java.awt.Color(0, 0, 0));
              lblPorcentajeValidos.setText("PORCENTAJE TOKENS VALIDOS: ");
              lblPorcentajeValidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

              lblTokensNoUtilizados.setForeground(new java.awt.Color(0, 0, 0));
              lblTokensNoUtilizados.setText("TOKEN NO UTILIZADOS:");
              lblTokensNoUtilizados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

              javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
              jPanel1.setLayout(jPanel1Layout);
              jPanel1Layout.setHorizontalGroup(
                     jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(lblTokensNoUtilizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(lblPorcentajeValidos, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())
                     .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblCantidadErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              jPanel1Layout.setVerticalGroup(
                     jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(lblCantidadErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(lblPorcentajeValidos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(lblTokensNoUtilizados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(54, Short.MAX_VALUE))
              );

              btnSalir.setText("SALIR");
              btnSalir.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnSalirActionPerformed(evt);
                     }
              });

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(18, Short.MAX_VALUE))
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(0, 0, 0))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(0, 0, 0))
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
              this.dispose();
       }//GEN-LAST:event_btnSalirActionPerformed

       private void cargarTokensNoUtilizados(String [] noUtilizados){
              String tokensNoUsados=lblTokensNoUtilizados.getText();
              for (int i = 0; i < noUtilizados.length; i++) {
                     tokensNoUsados+=" "+noUtilizados[i];
              }
              lblTokensNoUtilizados.setText(tokensNoUsados);
       }
       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnSalir;
       private javax.swing.JPanel contenedor;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JPanel jPanel1;
       private javax.swing.JLabel lblCantidadErrores;
       private javax.swing.JLabel lblPorcentajeValidos;
       private javax.swing.JLabel lblTokensNoUtilizados;
       // End of variables declaration//GEN-END:variables
}
