package com.ronaldo.analizadorlexico.frontend.dialogs;

import com.ronaldo.analizadorlexico.backend.enums.TipoToken;
import com.ronaldo.analizadorlexico.backend.token.Token;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronaldo
 */
public class ReporteErroresDialog extends javax.swing.JDialog {
       
       /**
        * Creates new form ReporteErroresDialog
        */
       public ReporteErroresDialog(List<Token> tokens) {
              initComponents();
              setTitle("reporte errores");
              cargarTabla(tokens);
       }

       /**
        * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              contenedor = new javax.swing.JPanel();
              jLabel1 = new javax.swing.JLabel();
              jScrollPane1 = new javax.swing.JScrollPane();
              tablaErrores = new javax.swing.JTable();
              btnCerrar = new javax.swing.JButton();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

              contenedor.setBackground(new java.awt.Color(204, 204, 204));

              jLabel1.setBackground(new java.awt.Color(255, 51, 0));
              jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 48)); // NOI18N
              jLabel1.setForeground(new java.awt.Color(0, 0, 0));
              jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel1.setText("REPORTE DE ERRORES");
              jLabel1.setOpaque(true);

              tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
                     new Object [][] {

                     },
                     new String [] {
                            "Cadena", "Fila", "Columna"
                     }
              ));
              jScrollPane1.setViewportView(tablaErrores);

              btnCerrar.setText("Cerrar");
              btnCerrar.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            btnCerrarActionPerformed(evt);
                     }
              });

              javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
              contenedor.setLayout(contenedorLayout);
              contenedorLayout.setHorizontalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(46, Short.MAX_VALUE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              contenedorLayout.setVerticalGroup(
                     contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 33, Short.MAX_VALUE))
              );

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
              this.dispose();
       }//GEN-LAST:event_btnCerrarActionPerformed

       private void cargarTabla(List<Token> tokens) {
              if (tokens == null) {
                     JOptionPane.showMessageDialog(this, "no hay errores para el reporte", "sin errores", JOptionPane.INFORMATION_MESSAGE);
                     return;
              }
              DefaultTableModel modelo = (DefaultTableModel) tablaErrores.getModel();
              for (int i = 0; i < tokens.size(); i++) {
                     if (tokens.get(i).getTipo().equals(TipoToken.ERROR.getNombre())) {
                            modelo.addRow(new Object[]{tokens.get(i).getLexema(),
                                   tokens.get(i).getFila()+1, tokens.get(i).getColumna()+1});
                     }
                     
              }
       }
       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JButton btnCerrar;
       private javax.swing.JPanel contenedor;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JScrollPane jScrollPane1;
       private javax.swing.JTable tablaErrores;
       // End of variables declaration//GEN-END:variables
}
